# Generated by Django 4.2.6 on 2023-11-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("groups", "0001_initial"),
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="posts",
            field=models.ManyToManyField(
                blank=True, related_name="groups", to="posts.post"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="groupmember", unique_together={("group", "user")},
        ),
    ]
